language: ruby
rvm:
- 2.0.0
deploy:
  provider: heroku
  api_key:
    secure: BZmk6dL/EpKfK9/+aRYuq2LTGi3nrHfQFmLRich12UD8Iif7u/aRUxCw1tlZOLcNJ92J3lzjfAvWfW0NBIc4j9l6PZvAlldfktVk2MewKHwnPlqtPaiOfC7nQH2kTJF5YvFNP5DMK3eXXARYbFnha1/3jgX1pL+WdMWWhzMeMSI=
  app: sleepy-retreat-4094
  on:
    repo: Basis104/rakuten-api
